### ISSUE TITLE
Extension not showing snippet loader version 

### ISSUE THREAD

**Issue by ol1000** [akamai/boomerang-inspector#12]
Hi Nic, when using the new extension from Chrome store, we dont see the snippet loader version 

![Screenshot 2021-02-15 at 08 49 26](https://user-images.githubusercontent.com/3727480/108086435-461dbe80-706e-11eb-977f-acf4f387f4eb.jpg)

I have tried with both origin and edge injection

**Comment by simonhearne** [comment]
Fixed in #14
